import type { Metadata } from "next";
import "../css/globals.css";
import 'swiper/css';
import 'swiper/css/pagination';
import 'leaflet/dist/leaflet.css';
import 'leaflet/dist/images/marker-icon.png'
import 'leaflet/dist/leaflet.css'
import { ReduxProvider } from "@/redux/provider";
import { interFont } from "@/utils/font";
import { ProviderNextUI } from "@/lib/nextProvider";



export const metadata: Metadata = {
  icons: {
    icon: "https://pengaduan-web.vercel.app/logo.svg"
  },
  title: "PT CITRA PRADANA MANDIRI TBK",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body suppressHydrationWarning={true} >
          <ProviderNextUI>
            <div className={` ${interFont.className} dark:bg-boxdark-2 dark:text-bodydark`}>
              {children}
            </div>
          </ProviderNextUI>
        </body>
      </html>
    </ReduxProvider>
  );
}
